/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBox: typeof import('vistara-components')['VBox']
    VCarousel: typeof import('vistara-components')['VCarousel']
    VDivider: typeof import('vistara-components')['VDivider']
    VPdfView: typeof import('vistara-components')['VPdfView']
  }
}
